name: todo_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^3.2.0
  kiwi: 2.0.0

dev_dependencies:
  bloc_test: ^3.1.0
  build_runner: 1.10.3
  flutter_test:
    sdk: flutter
  kiwi_generator: ^2.0.0
  mockito: 4.1.1
    
flutter:
  uses-material-design: true
